version: "3.8"
services:
  kinobook-db:
    container_name: kinobook-db
    image: postgres:14
    environment:
      POSTGRES_DB: kinobook-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5555:5432"
    volumes:
      - .:/var/lib/kinobook_db/data
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G
