# docker-compose -f elastic.yaml up -d

version: "3.0"
services:
  kinobook-elastic:
    container_name: kinobook-elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xmx512m -Xms512m"
    # networks:
    #   - es-net
    ports:
      - 9200:9200
# networks:
#   es-net:
#     driver: bridge
