export enum InterfacesTokens {
  AUTH_SERVICE = 'IAUTH_SERVICE',
  JWT_SERVICE = 'IJWT_SERVICE',
  USER_SERVICE = 'IUSER_SERVICE',
  MOVIE_SERVICE = 'IMOVIE_SERVICE',
  FILE_SERVICE = 'IFILE_SERVICE',
  GENRE_SERVICE = 'IGENRE_SERVICE',
  ACTOR_SERVICE = 'IACTOR_SERVICE',
  WRITER_SERVICE = 'IWRITER_SERVICE',
  COUNTRY_SERVICE = 'ICOUNTRY_SERVICE',
  BOOKMARK_SERVICE = 'IBOOKMARK_SERVICE',
  VIEWED_SERVICE = 'IVIEWED_SERVICE',
  AUTH_GUARD = 'AUTH_GUARD',
}
